name: Deploy Lambda to AWS

on:
    push:
        branches:
            - dev
            - feature-ci

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Zip Lambda Function
              run: zip lambda.zip lambda_function.py

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
                  aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
                  aws-region: us-east-1

            - name: Upload to S3
              run: aws s3 cp lambda.zip s3://smitten-test1-bucket/lambda.zip

            - name: Deploy to Lambda
              run: |
                  aws lambda update-function-code \
                    --function-name empHandler \
                    --s3-bucket smitten-test1-bucket \
                    --s3-key lambda.zip
